name: Flow
on: push
jobs:
  build-web:
    name: Build (Web)
    runs-on: ubuntu-latest
    container: kuviman/geng
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: cargo geng build --web --release
      - name: Upload artifacts (web)
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: target/geng
  deploy-pages:
    name: Deploy Pages
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'kuviman'
    runs-on: ubuntu-latest
    needs:
      - build-web
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web